### ISSUE TITLE
CTR mode is incompatible with OpenSSL implementation

### ISSUE THREAD

**Issue by tishion** [kokke/tiny-AES-c#120]
Hi I tried to use CTR 128 bit  to process the cipher data generated by OpenSSL AES CTR 128 bit mode, but it can only get the correct output at the first xcrypt operation. The subsequent xcrypt operations all gave the invalid output. I believe there are some differences in the IV increasing between tiny-AES and OpenSSL.

**Comment by meeidol-luo** [comment]
same problem

**Comment by kokke** [comment]
Hi @tishion 

I agree: It sounds like there is a difference between how OpenSSL handles the IV increment and how this library does it. The difference is probably that this library increments the counter after each 16-byte block, where the OpenSSL may only increment after encrypting the entire payload (consisting of several blocks).

You could use the function `AES_ctx_set_iv` to control the IV (counter) and gain compatibility with OpenSSL in CTR-mode.

**Comment by tishion** [comment]
Alright.
But it sounds not good to me, because i need to get the count of the round in each xcrypt operation and then handle the IV by myself.  I just turned to OpenSSL for my purpose.

Anyway, thank you so much for sharing this nice small implementation!

**Hope this thread will make the other people know this difference and not to go the wrong way.**

**Comment by kokke** [comment]
>But it sounds not good to me, because i need to get the count of the round in each xcrypt operation and then handle the IV by myself. I just turned to OpenSSL for my purpose.

You just need to re-initialize the IV before each call to `AES_CTR_xcrypt_buffer`, but you can probably avoid that by using OpenSSL.
OpenSSL does a lot of things for you, that this library does not, e.g. handle IVs and padding etc.
You also potentially gain a lot of speed by using OpenSSL, because this code is pretty slow.

> **Hope this thread will make the other people know this difference and not to go the wrong way.**

The need to manually handle the IV(counter) in CTR-mode has been discussed in other threads as well:

https://github.com/kokke/tiny-AES-c/issues/98
https://github.com/kokke/tiny-AES-c/issues/102
https://github.com/kokke/tiny-AES-c/issues/115
