### ISSUE TITLE
Multiply function does not work correctly

### ISSUE THREAD

**Issue by ponchikDnika** [kokke/tiny-AES-c#128]
The result of multiplication {0x53} and {0xca} is 8 but should be 1 because the elements {53} and {CA} are multiplicative inverses.

**Comment by kokke** [comment]
Hi @ponchikDnika and thanks for your interest in this project.

I think you are missing an assumption someway or somehow, since a failed multiplication implementation over the Galois-field, should make the library fail the NIST-tests.

It should also make the library incompatible with other AES implementations, which I have yet to experience.

Please provide a test-case that demonstrates how the alleged bug makes encryption/decryption fail.

**Comment by kokke** [comment]
Closing as it seems there is some misunderstanding behind the opening of this issue. 

Feel free to reopen, if you encounter a specific issue with the functionality of the project.
