### ISSUE TITLE
Please add padding PKCS5Padding

### ISSUE THREAD

**Issue by anonym24** [kokke/tiny-AES-c#137]

**Comment by CunningLogic** [comment]
PKCS5 is for 64bit block size, AES is 128. You would want PKCS7, which would support AES block size.

**Comment by anonym24** [comment]
@CunningLogic I don't know but `"AES/ECB/PKCS5Padding"` was working ok on Android

**Comment by CunningLogic** [comment]
Android isn't likely using PKCS5, but probably just playing safe and using PKCS7 for AES.

**Comment by anonym24** [comment]
@CunningLogic I have no idea) but yes I think they do it like you said

**Comment by kokke** [comment]
Hi @anonym24 

This library doesn't support padding out of the box, but PKCS7 seems pretty easy to implement on your own. It's a generalization over PKCS5, see https://crypto.stackexchange.com/questions/9043/

I don't want to support any padding schemes since it ends up taking up more code + space than the AES library.
