### ISSUE TITLE
C++ version - my first release ever!

### ISSUE THREAD

**Issue by ifknot** [kokke/tiny-AES-c#139]
https://github.com/ifknot/AES-CPP17/releases/tag/v0.1.1-beta

**Comment by kokke** [comment]
Hi @ifknot and congratulations on the release :)

I haven't had the time (yet) to take a good look at your implementation, but it seems it would be a good match for desktop applications wanting AES encryption.

Have you made any performance-optimizations compared to this version? There are a lot of low-hanging fruits to pick here (issue + PR section has many), that I haven't picked, because it could cost a byte or two in code size. 

By the way, thanks for participating in the issues section - I saw you responding to #141 :)

**Comment by ifknot** [comment]
Hi @kokke thanks my implementation is for fun and learning - the only optimization is loop unrolling as I wondered if manual loop unrolling offered any benefit over compiler optimization e.g. CLang -Ofast  and surprisingly it does seem to: (on my system ymmv)

https://github.com/ifknot/AES-CPP17/wiki

And as you suggested a direct performance comparison kokke vs ifknot shows in favour ifknot with CLang: (on my system ymmv)

https://github.com/ifknot/AES-CPP17/wiki/Perfomance-Comparison-Kokke

The perfomance tests and R script are in the "tests" folder.

I am waiting for a Pi Zero to try cross compiling to in order to compare performance there and memory footprints - I'm hoping that using the Template Factory pattern in C++ should mean a small memory footprint?

Also I cant find the NIST advice on xcrypt for CTR mode that you mentioned?

Thanks for your interest 🙂



________________________________
