### ISSUE TITLE
CBC/CTR Encrypt/Decrypt large buffers

### ISSUE THREAD

**Issue by Youw** [kokke/tiny-AES-c#172]
At this moment, `AES_CBC_encrypt_buffer`/`AES_CBC_decrypt_buffer`/`AES_CTR_xcrypt_buffer` uses `uint32_t` as a `length` parameter type, which makes impossible to use this functions with buffers larger than 4GB on 64bit systems.

So for `AES_CBC_encrypt_buffer` (maybe `AES_CTR_xcrypt_buffer` too, haven't tried) a client-side workaround is possible, but for `AES_CBC_decrypt_buffer` ~~it becomes too complicated~~ well, same workaround is required.

Simply replacing `uint32_t` with `size_t` for function parameter and iterator variable type looks like solves the issue.

I can prepare a patch/PR with the change, but before I do so, want to ask: is there a particular reason that I'm missing why the buffer size is explicitly limited to 32bit data len size?

**Comment by kokke** [comment]
Hi @Youw and thanks for your interest in this project :)

Yes it makes it impossible to use CBC with buffers larger than 4 GB, but not to work with files or streams larger than 4 GB.
You can just split the file/stream/buffer up in small chunks and work in them one at a time. You don't need to hold it all in memory.

CBC works like this [from wikipedia]

![From Wiki](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/CBC_encryption.svg/900px-CBC_encryption.svg.png)

So the encrypted text becomes the IV for each next block. That means you can just cut the file/stream up in small pieces, so you actually don't need a buffer larger than 16 bytes to decrypt larger objects.

There may be a small convenience gain in a rare use-case, but since you don't need it, and I can't remember the last time I allocated 4 GB memory just like that :) I will not merge this and I will decline your PR.

Thank you for taking the effort to trying to improve this library however.

**Comment by Youw** [comment]
Yeap, this is exactly what I called a "workaround", even though it is probably a better idea to perform operations in iterations/smaller chunks.

My motivation for this change is also of different origin:
Imagine me as a regular C++ developer: when I have a chank of data (even it is jut a few bytes size) it is stored in some kind of container (std::vector<uint8_t>, std::array<uint8_t>) or a memory view (std::span<uint8_t>) and I want to pass this data into tiny AES, using its API. Regardless of what container type is, the usage would look something like:
```cpp
AES_CBC_encrypt_buffer(ctx, buffer.data(), buffer.size());
                                               // ^^ the problem is here
```
`.size()` method in this case always return `size_t`, and implicit conversion from `size_t` to `uint32_t` - that's at least a compiler warning (or an error - all my projects are using `-Werror`), not to mention real runtime issue that _might happen_.

To make the program strictly correct, one must explicitly cast `size_t` to `uint32_t` _**and** make a runtime check_:
```cpp
if (buffer.size() > UINT32_MAX)
    throw std::runtime_error("Our C++ wrapper over TinyAES library doesn't support buffers larger than 4 GB");

AES_CBC_encrypt_buffer(ctx, buffer.data(), uint32_t(buffer.size()));

// this version of program is "strictly correct" from C++ POV
```

But as you mentioned earlier, this limitation shouldn't exist, as subsiquent passing of the buffer split into chanks would do exactly what we want. But that requires writing extra amount of code, which basically duplicates some of the implementation of what TinyAES already has.
```cpp
// I'm not ready to provide a sample implementation for it. It is not elegant, nor trivial.
```

---
TL;DL:
With suggested change, the usage is so much easier, if:
- a client code already has a `uint8_t* buf; size_t buf_size;` pair;
- `buf_size` is unknown, i.e.: no guarantee that it is smaller than `UINT32_MAX`;
- "strict correctness" of the program matters.

Based on my experience, all 3 of the above is a common case.

**Comment by Nable80** [comment]
There's one more reason to use ``size_t`` instead of ``uint32_t``: it's allowed to be 16-bit wide, so it may save some bytes on 8/16-bit MCUs (avoid unnecessary overhead for parameter passing).

Using ``size_t`` is definitely the most natural way of passing sizes of objects in C and C++.

**Comment by kokke** [comment]
>There's one more reason to use size_t instead of uint32_t: it's allowed to be 16-bit wide, so it may save some bytes on 8/16-bit MCUs (avoid unnecessary overhead for parameter passing).

That was my biggest grief - object code on 8 bit platforms will be bloated if using 64-bit integers, but on e.g. AVR, size_t is 16-bit. 

Let's do the change..
