### ISSUE TITLE
Tried to add new clearText but the code is not picking up the changed clear text

### ISSUE THREAD

**Issue by abhowmik** [kokke/tiny-AES-c#176]
Hi,
I changed the code in the aes.c such that plain text and the keys reflect the plaintext I want to encrypt
plain-text:
    ansbhowm
    123-456-7890
    111.111.11.11
    f69f2445df4f9b17ad2b417be66c3710

but when I run 
make aes.c 
gcc -DAES256=1 aes.c test.c -o run_test
./run_test I keep getting the following. My question what do I have to do such that the aes.c picks up my changed cleartexts:
plain text:
6bc1bee22e409f96e93d7e117393172aae2d8a571e03ac9c9eb76fac45af8e51
ae2d8a571e03ac9c9eb76fac45af8e5130c81c46a35ce411e5fbc1191a0a52ef
30c81c46a35ce411e5fbc1191a0a52eff69f2445df4f9b17ad2b417be66c3710
f69f2445df4f9b17ad2b417be66c37102b7e151628aed2a6abf7158809cf4f3c

key:
2b7e151628aed2a6abf7158809cf4f3c90146ee4fe7f0000f900f148012ea37a

ciphertext:
c7bb1b6923835397b278d42cff39fc1dae2d8a571e03ac9c9eb76fac45af8e51
23417692a5cebfed50ebbba3ba19041330c81c46a35ce411e5fbc1191a0a52ef
88d6a87cc158e01399fae12e616a4aa0f69f2445df4f9b17ad2b417be66c3710
4a37959ccce96a9f007c4ed90320a76a2b7e151628aed2a6abf7158809cf4f3c

Please Advise

**Comment by kokke** [comment]
Hi @abhowmik and thanks for your interest in this project :)

I can't really see what it is you are trying, but if you are trying to change the stuff that runs in the test-file (seems so) that is where you should try changing the key and plain-text etc., i.e. in `test.c` instead of in `aes.c`.

The issues-section is reserved for bug-tracking, and a question such as this is much better answered on stackoverflow.com or some other forum, than here.

Closing the issue.
