### ISSUE TITLE
How to pass the data type as string for key and plain_test varibles  in test_encrypt_ecb_verbose method

### ISSUE THREAD

**Issue by Yogeshkc7** [kokke/tiny-AES-c#203]
HI

In the method test_encrypt_ecb_verbose, how can we use the key and plain text variable as string input.
eg: 
key[16]={"1234567890123456"};
plain_text[16]={''0987654321123456"}; //Can we use plain text as 16 instead of 64 as array size?

Thanks

**Comment by alyfreym** [comment]
Same here. any answer?

**Comment by hamza7171** [comment]
same here. any success?

**Comment by davidbrucecousins** [comment]
Hi, I'd recommend writing a function to do that. C++ would let you overload the = operator, but not C.  store the value in a string , and parse it 2 characters at a time into a uint8_t , then store in the uint8_t. repeat over the required length. I am sure the PR would be well received!

**Comment by MasterVitronic** [comment]
I think this might help

https://gist.github.com/sdrsdr/0a69e9becf056b0d410e56336d083fd1

**Comment by kokke** [comment]
Hey 😃 

I'd say this is a question about usage and not about a problem/issue with the library. 

I would honestly even categorize this as a quite basic C programming-question. StackOverflow.com is a much better fit for these.
You will definitely get much faster feedback there than from me 😄🤷‍♂️ I don't have a lot of time to do support for my public repos.

In general AES works with binary data. You need to convert to/from binary yourself. A string in C is just [binary data encoded in a certain way](https://en.wikipedia.org/wiki/C_string_handling#Character_encodings).

The key always has a pre-defined size: 
- 128 bits / 16 bytes for AES128
- 192 bits / 24 bytes for AES192
- 256 bits / 32 bytes for AES256

So you have a few options for using a string as key:

- Use the string as-is and pad/truncate accordingly (e.g. using [PKCS7](https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS7)) to get desired length (not the best choice)
- Use a hash of the string, consider [salt](https://en.wikipedia.org/wiki/Salt_(cryptography)) & [pepper](https://en.wikipedia.org/wiki/Pepper_(cryptography)) also (better option IMO)
- Generate cryptographically random data and use that as the key (also a great choice)

The goal is to get high [entropy](https://en.wikipedia.org/wiki/Entropy_(information_theory)) in the key. Using raw strings defeat this purpose.


If you use one of the [block-cipher modes of operation](https://en.wikipedia.org/wiki/Block_cipher) (and not e.g. CTR which is a [streaming mode-of-operation](https://en.wikipedia.org/wiki/Stream_cipher)) you need to pad the input-data so it's always a multiple of 16 bytes.

Variations of this question has been raised multiple times previously, e.g. these:
- https://github.com/kokke/tiny-AES-c/issues/131
- https://github.com/kokke/tiny-AES-c/issues/133
- https://github.com/kokke/tiny-AES-c/issues/14
- https://github.com/kokke/tiny-AES-c/issues/158
- https://github.com/kokke/tiny-AES-c/issues/184


Closing the issue because it's a usage-question.

---

> store the value in a string , and parse it 2 characters at a time into a uint8_t , then store in the uint8_t. repeat over the required length. I am sure the PR would be well received!

Please don't do this (for the reasons stated above).
