### ISSUE TITLE
Is it possible to support AES128, AES192, and AES256 simultaneously in the same project?

### ISSUE THREAD

**Issue by marunguy** [kokke/tiny-AES-c#231]
It seems that only one of AES128, AES192, and AES256 can be used in the same project.
Is there a way to use them simultaneously in the same project?

**Comment by kokke** [comment]
Hi @marunguy :)

It is possible yes, but you would have to rewrite the code slighty.

You can add a parameter/argument that decided whether to use AES128/192/256 and replace `#ifdef`s with normal if-statements (that are decided at runtime instead of compile time).

If you know your way around the preprocessor you can also make some `#include`-hacks to handle it at compile-time, but I would recommend against that approach.
