### ISSUE TITLE
ECB or CBC

### ISSUE THREAD

**Issue by acad2** [kokke/tiny-AES-c#64]
The readme says, 

> GCC size output when only ECB mode is ...

but the command is
`arm-none-eabi-gcc -Os -c aes.c -DCBC=0`

Is that a typo?

**Comment by kokke** [comment]
Hi @acad2 and thank you for taking an interest in this project :)

It is not a typo. I guess you are confused about the `-DCBC=0` part?
Both ECB and CBC are enabled per default.
Defining CBC to 0 effectively disables CBC mode, leaving only ECB mode enabled.

Does that answer your question sufficiently :) ?

**Comment by acad2** [comment]
Sure, thanks for your prompt reply.
Just wondering, do you have plan to implement other ciphers as well?

**Comment by kokke** [comment]
I have a wish to implement OFB-mode sometime in the future: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Output_Feedback_.28OFB.29

I like it because it is simple and symmetric (encryption and decryption is the same operation).

Check out some of the project forks, or sift through the pull requests. Others have implemented other modes of operations. 

I lost track of the different working forks out there sometime last year, but I know other people have implemented different modes of operation using this library.

**Comment by kokke** [comment]
I am marking this issue as closed, just to please my "OCD" ;) not to shut you up or anything.
