### ISSUE TITLE
Have you used this with AVR?

### ISSUE THREAD

**Issue by jn23sahoo** [kokke/tiny-AES-c#72]
I'm facing problem on encryption. It generating values here then 255. So how to manage that? Can you please share implementation of this code on AVR?

**Comment by kokke** [comment]
Hi @jn23sahoo 

This implementation is 8-bit oriented, which means it should be able to run on AVR processors without any problems. 

Its been a few years since the last time I used it on AVR chips, but it should indeed be compatible with AVR processors and arduinos etc. But to answer the question in your title: Yes I have used this code with AVR processors.

Other users are using this project on AVR as well.
See this issue for a description of how to use with Arduino: https://github.com/kokke/tiny-AES-c/issues/68

**Comment by jn23sahoo** [comment]
I'm getting encrypted test as some of them are having integer value more then 255. So here ASCII can't work. I have to use UTF-8. But there is library to run UTF-8 on AVR C

**Comment by kokke** [comment]
I really don't mean to be rude, but I can't understand your question - I understood the part about whether or not the code works for AVR.

However I don't understand the part with integer value > 255 and the parts about ASCII and UTF-8.

You should be working with binary data, such that binary data input gives a binary data output.

If you would like me to help you, please explain further, or maybe upload a piece of code to show what you are trying to do :)

**Comment by jn23sahoo** [comment]
**## See my code**
`#define AES256 1
#define CBC 1

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "aes/aes.h"
#include "aes/aes.c"

static char padding[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,14,15,16};
void gen_random(char *s, const int len);
char* addPadding(char* str);
char* removePadding(char* str);

int main() {
    char data[] = "Bhai Kyun Nahi Hota Encryption!";
    char key[] = "QWERTYUIOP";
    char iv[] = "asdfghjkl";
    char encBuffer[64];
    char decBuffer[64];
    AES_CBC_encrypt_buffer(encBuffer,addPadding(data),strlen(addPadding(data)),key,iv);
    printf("\nEncrypted string: %s",encBuffer);
    AES_CBC_decrypt_buffer(decBuffer,encBuffer,strlen(encBuffer),key,iv);
    printf("\nDecrypted string: %s",decBuffer);
    return 0;
}

void gen_random(char *s, const int len) {
    static const char alphanum[] =     "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    for (int i = 0; i < len; ++i) {
        s[i] = alphanum[rand() % (sizeof(alphanum) - 1)];
    }

    s[len] = 0;
}

char* addPadding(char* str)
{
    char *ptr;
    uint8_t  result = (strlen(str) % 16);
    uint8_t numOfPadding = 16 - result;
    ptr = (char*) calloc(strlen(str)+numOfPadding, sizeof(char));
    strcpy(ptr,str);
    printf("\n%s",ptr);
    for (int i = strlen(str); i < (strlen(str)+numOfPadding)-1 ; ++i) {
        ptr[i] = 0;//padding[numOfPadding];
    }
    ptr[strlen(str)+numOfPadding] = 0;
    return ptr;
}

char* removePadding(char* str)
{
    return strtok(str,padding);
}`
**## Output:**
Bhai Kyun Nahi Hota Encryption!
Bhai Kyun Nahi Hota Encryption!
�8���7����H�3��z>�3�t�4CF^B����G^�b�@ASCII
Decrypted string: Bhai Kyun Nahi Hota Encryption!
 Tell me why these "�" are coming?

**Comment by kokke** [comment]
You are incorrectly assuming that encrypting ASCII text becomes ASCII as well, after encryption.
This is not the case! 

It is not possible for a byte to be > 255.
The �'s are because the values of the characters are outside of the printable range but `printf("%s", ...)` expects a zero-terminated string containing characters in the printable range.

Print out each character as a hex string instead - see the test-code for this project for an example.

**Comment by kokke** [comment]
The classic ASCII character set consists of integer values from 0 -> 127.
Check http://www.asciitable.com/ for a reference.

When you encrypt an ASCII-encoded string, it becomes transformed to a binary blob of data.
You can't print this binary data using `printf` in combination with the `%s`-format string.
The `%s`-format string print chars until it sees a binary zero (0x00) - the zero termination character.

After encrypting an ASCII-encoded string, the guarantee of having a zero as last element is lost.
The guarantee of all chars in the array being in the printable range is also gone.
The data is simply not ASCII anymore. It is binary :)
