### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by FullNitrous** [kokke/tiny-AES-c#74]
In the test.c file, it does `#include "aes.h"` as the library. This is incorrect and will lead to linker errors. Please replace that with `#include "aes.c"` instead. Then it works fine at compilation. I'm only writing this because it may lead to confusion. Although I would like to know why the header file does not `#include "aes.c"`. Seems a bit odd. Besides that, great library, really nice performance.

**Comment by kokke** [comment]
No this is entirely intended and not at all incorrect :)

`#include`-ing a C source file is not a recommended practice in C-programming.
I think it takes place more often in C++ code bases, but it is not a recommended practice with C modules.

You need to add `aes.c` to the list of C-files being compiled, otherwise you will get a linker error.
And yes that error can be solved in some instances by including the C-file.

I will explain further why this is not a recommended practice.
See these posts from StackOverflow (first hits on google) for more information on why this is not a good practice.

https://stackoverflow.com/questions/232693/including-one-c-source-file-in-another
https://stackoverflow.com/questions/11334371/cant-we-include-c-file
https://stackoverflow.com/questions/11849868/is-it-ok-to-include-a-c-file-in-another-c-file

**Comment by FullNitrous** [comment]
Yeah ok, thanks.

**Comment by kokke** [comment]
I did not know that particular mode of operation before googling it. It seems like a twist on CTR mode from glancing quickly through a description.

I have not implemented CTR nor XTS myself, but am pretty sure some of the forks of this project has done CTR mode. Not sure about XTS though. Would need to look through the forks or spend some time googling - I'm online through my phone now, so basically AFK ;)

It's typically not horribly difficult to implement a new mode of operation, so maybe you got the chops for it yourself? :) I' gladly help you.

ECB is sort of the basic primitive that other modes build upon. CBC is a good example to learn from :)

**Comment by kokke** [comment]
Oh and by the way @FullNitrous , forgot to thank you for the kind words :)

**Comment by FullNitrous** [comment]
Yeah no problem, i'll close this for now. Though i might implement those other modes of operation if i ever get the time to :)
