### ISSUE TITLE
Memory access violation

### ISSUE THREAD

**Issue by Tsikite** [kokke/tiny-AES-c#80]
In KeyExpansion, the line which initialize the first RoundKey should be 
`memcpy(RoundKey, Key, AES_KEYLEN);`

Using AES_keyExpSize as the length of 'Key' causes memory issues.

I also think it is best that AES_init_ctx should have arrays initialization:
`memset(ctx->RoundKey, 0, AES_keyExpSize);
#if (defined(CBC) && (CBC == 1)) || (defined(CTR) && (CTR == 1))
  memset(ctx->Iv, 0, AES_BLOCKLEN);
#endif`

End up looking like this:
`void AES_init_ctx(struct AES_ctx* ctx, const uint8_t* key)
{
  memset(ctx->RoundKey, 0, AES_keyExpSize);
#if (defined(CBC) && (CBC == 1)) || (defined(CTR) && (CTR == 1))
  memset(ctx->Iv, 0, AES_BLOCKLEN);
#endif
  KeyExpansion(ctx->RoundKey, key);
}`

**Comment by kokke** [comment]
Hi @Tsikite - you're right that we shouldn't read AES_keyExpSize from the key-variable.
The correct code seem to be just below the `memcpy()` but have been commented out.

We have recently made a few changes to the API and it seem a few bugs have crept in.

Thanks for notifying, I will get them fixed ASAP. 

However, I am not sure I agree about zero-initializing under initialization. What is your argument for needing that?

**Comment by kokke** [comment]
Memory access violation fixed in [commit 6dfe50fd61b510f2edb46ac6453bda7dffd95ebf](https://github.com/kokke/tiny-AES-c/commit/6dfe50fd61b510f2edb46ac6453bda7dffd95ebf).

**Comment by Tsikite** [comment]
Hi kokke,

RoundKey array indeed does not need initialization. As for iv array, it is possible to use ctx without defining specific iv. This may will result in encrypted buffer that is undecryptable because the iv array is uninitialized and unknown. Therefore I think it is best (btw, like in some other implementations of AES I used) that iv will be set to zero if not set by the user.

Of-course one should know AES mechanism and how to use the API but this kind of error can be avoided.

**Comment by kokke** [comment]
You are right that if both the encrypting party AND the decrypting party is using the library wrong, e.g. using CBC mode without initializing an IV, then zero-initializing the IV would make it "work" for both parties.
However it would also make the cipher-text trivially breakable since the IV is all-zeros. 
In other words, it breaks security trying to fix a problem stemming from incorrect usage.

This library is meant to be a small low-level encryption primitive with minimal error-checking, such that correct usage can fit in very small devices.

**Comment by Tsikite** [comment]
Agree!

Thanks

**Comment by kokke** [comment]
@Tsikite you're welcome :)

Thanks a lot for pointing out the memory access violation.
