### ISSUE TITLE
C++ compability

### ISSUE THREAD

**Issue by Skycoder42** [kokke/tiny-AES-c#83]
In order to make the library more compatible with C++, please add the `extern "C"` part to the header:

```
#ifdef __cplusplus
extern "C" {
#endif

    // ... header code

#ifdef __cplusplus
}
#endif
```
This way, the files can be used in a c++ project without adding that part to every include.

**Comment by kokke** [comment]
Hi @Skycoder42 and season's greetings to you :)

Thanks for your interest in improving the project, I really appreciate it.

If the project contained more than a single header-file, I would have agreed with you.
Since it doesn't, my first instinct is to be rude and let the C++ crowd wrap the single `#include`-directive in `extern C { ... }`.

The header already contains a lot of preprocessor directives so I feel this addition "pollutes" the header unnecessarily. 

It takes two `#if - #endif` pairs to add C++ support in C, while it only requires the `extern "C"` to support C-code in C++.

Can you follow my argument or am I babbling :) ?

**Comment by Skycoder42** [comment]
If you take it that way: It's only 5 lines in one file, but many explicit extern statements for all the c++ files it is used in. ;) Also, adding this would prevent a cpp developer from accidentally compiling the c file with a c++ compiler, which can sometimes lead to undefined behaviour. (that would result in a linker error, as the header wants c symbols, but the obj file defines c++).

If you don't want to "pollute" the main header, why not add a new `aes.hpp` file and add it to the readme. so cpp developers can include that one instead. The file could look like this:

```cpp
#ifndef _AES_HPP_
#define _AES_HPP_

#ifndef __cplusplus
#error Do not include the hpp header in a c project!
#endif //__cplusplus

extern "C" {
#include "aes.h"
}

#endif //_AES_HPP_
```

**Comment by kokke** [comment]
Hey the .hpp header is a really nice idea - let me add the file to the repo immediately.

**Comment by kokke** [comment]
Thanks for your contribution @Skycoder42 :) 👍 

https://github.com/kokke/tiny-AES-c/blob/master/aes.hpp
