### ISSUE TITLE
sizes larger than 6400000 bytes crash

### ISSUE THREAD

**Issue by nd95** [kokke/tiny-AES-c#97]
Rewrote the test script to test larger file sizes and when I try anything past 6400000 bytes the program seg faults

**Comment by kokke** [comment]
Hi @nd95 and thanks for taking an interest in this project :)

I am not sure I understand the problem you are facing. 

> Rewrote the test script to test larger file sizes

I am not sure what you are referring to, as the [test file](https://github.com/kokke/tiny-AES-c/blob/master/test.c) does not read files.

I would need to see the changes you have made to the test-code, in order to be able to help you assess the reason for your troubles.

**Comment by nd95** [comment]
Hi @kokke 
Thanks for the reply.

https://github.com/nd95/Tiny-AES-implementation-/tree/master

There is the github link my apologies. Please let me know what you find!

--FOR SCIENCE

**Comment by kokke** [comment]
I haven't run your code, but it looks like you're breaking the stack:


`test_xcrypt_ctr()` allocates on the stack:

```C
static void test_xcrypt_ctr(int size)
{
    ...
    uint8_t in[size]; /* this is allocated on the stack */
    ...
}
```

It allocates as many bytes as `main()` tells it to:

```C
int main(int argc, char** argv)
{
    ...
    int size = atoi(argv[1]);
    ...
    test_xcrypt_ctr(size);
    ...
}
```


So I will repeat my initial suspicion: You are allocating way too much on the stack.

Allocate memory on the heap or do it statically instead of using the stack for such large pieces of memory.

**Comment by kokke** [comment]
Hi again @nd95 

You could also consider changing your approach. 
You are currently allocating memory to hold the whole file. 
You only need to allocate and work on 16 bytes at a time. 
The current approach will fail once file sizes exceed memory available.

**Comment by kokke** [comment]
I will close this issue as your problem is stack overflow and not some bug in the library.

Do feel free to re-open the issue or just continue discussions despite the closed-status.

**Comment by nd95** [comment]
Ah thanks for the reply, that is a good idea. Thanks for the input! Hope I can finish this so that you may be able to use this driver one day!
